################################  Descriptive input fields
FIELD_DATE = "date"
FIELD_TICKER = "ticker"
FIELD_ISIN = "isin"
FIELD_CCY = "ccy"
FIELD_SECURITY_TYPE = "securityType"
FIELD_MARKET_SECTOR = "marketSector"
FIELD_SECURITY_TYPE2 = "securityType2"
FIELD_MARKET_SECTOR = "marketSector"
FIELD_EXCHANGE = "exchCode"
FIELD_EXCHANGE_DESCR = "Market or Index"
FIELD_FIGI = "figi"

################################   Market data input fields
FIELD_CLOSE = "Close"
FIELD_STOCK_SPLIT = "Stock Splits"
FIELD_DIVIDENDS = "Dividends"
FIELD_FX_RATES = "FX Rates"

################################   Transactions columns name
TRANSACTION_FIELD_BUY_SELL = "buy_sell"
TRANSACTION_FIELD_QUANTITIY = "quantity"
TRANSACTION_FIELD_PRICE = "price"
TRANSACTION_FIELD_CCY = "currency"
TRANSACTION_FIELD_ISIN = "isin"
TRANSACTION_FIELD_TR_DATE = "transaction_date"

VALUE_TRANSACTION_BUY = "B"
VALUE_TRANSACTION_SELL = "S"


################################   holdings/performance daily  fields
FIELD_EVAL_QUANTITY = "quantity"
FIELD_EVAL_MKTVALUE = "mkt_value"
FIELD_EVAL_MKTVALUE_BOD = "mkt_value_bod"
FIELD_EVAL_MKTVALUE_EOD = "mkt_value_eod"
FIELD_EVAL_MKTVALUE_LCL_CCY = "mkt_value_lcl_ccy"
FIELD_EVAL_MKTVALUE_BOD_LCL_CCY = "mkt_value_bod_lcl_ccy"
FIELD_EVAL_MKTVALUE_EOD_LCL_CCY = "mkt_value_eod_lcl_ccy"

FIELD_EVAL_M2M_BOD = "m2m_bod"
FIELD_EVAL_M2M_BOD_LCL_CCY = "m2m_bod_lcl_ccy"
FIELD_EVAL_TOTAL_RETURN_BASIS = "total_return_basis"
FIELD_EVAL_POSITION_BASIS = "position_basis"
FIELD_EVAL_TOTAL_RETURN_BASIS_LCL_CCY = "total_return_basis_lcl_ccy"
FIELD_EVAL_POSITION_BASIS_LCL_CCY = "position_basis_lcl_ccy"
FIELD_EVAL_MKTVALUE_WEIGHTS_HLDS = "weight_on_mkt_value_hlds"
FIELD_EVAL_TOTAL_RETURN_BASIS_WEIGHTS = "weight_on_total_return_basis"
FIELD_EVAL_POSITION_BASIS_WEIGHTS = "weight_on_position_basis"

FIELD_EVAL_PNL_LCL_CCY = "pnl_lcl_ccy"
FIELD_EVAL_PNL = "pnl"
FIELD_EVAL_RETURN_LCL_CCY = "return_lcl_ccy"
FIELD_EVAL_RETURN = "return"
FIELD_EVAL_RETURN_HLDS = "return_hlds"
FIELD_EVAL_RETURN_HLDS_LCL_CCY = "return_hlds_lcl_ccy"
FIELD_EVAL_CTR_TO_RETURN = "ctr_to_return"
FIELD_EVAL_CTR_TO_RETURN_LCL_CCY = "ctr_to_return_lcl_ccy"
FIELD_EVAL_CCY_RETURN = "ccy_return"
FIELD_EVAL_INCOME_PNL = "income_pnl"
FIELD_EVAL_INCOME_PNL_LCL_CCY = "income_pnl_lcl_ccy"
FIELD_EVAL_TRANSACTION_PNL = "transaction_pnl"
FIELD_EVAL_TRANSACTION_PNL_LCL_CCY = "transaction_pnl_lcl_ccy"
FIELD_EVAL_TRANSACTION_RETURN = "transaction_return"
FIELD_EVAL_TRANSACTION_RETURN_LCL_CCY = "transaction_return_lcl_ccy"

FIELD_EVAL_1D_RETURN_LCL_CCY = "1d_ret_lcl"
FIELD_EVAL_1W_RETURN_LCL_CCY = "1w_ret_lcl"
FIELD_EVAL_1M_RETURN_LCL_CCY = "1M_ret_lcl"
FIELD_EVAL_1Q_RETURN_LCL_CCY = "1Q_ret_lcl"
FIELD_EVAL_1Y_RETURN_LCL_CCY = "1Y_ret_lcl"
FIELD_EVAL_1D_RETURN = "1d_ret"
FIELD_EVAL_1W_RETURN = "1w_ret"
FIELD_EVAL_1M_RETURN = "1M_ret"
FIELD_EVAL_1Q_RETURN = "1Q_ret"
FIELD_EVAL_1Y_RETURN = "1Y_ret"
FIELD_EVAL_STD_DEV = "std_dev"
FIELD_EVAL_STD_DEV_LCL_CCY = "std_dev_lcl_ccy"
FIELD_EVAL_VAR_95 = "var_95"
FIELD_EVAL_VAR_99 = "var_99"
FIELD_EVAL_MEAN = "mean"
FIELD_EVAL_BETA = "beta"
FIELD_EVAL_SKEWNESS = "skewness"
FIELD_EVAL_SHARPE_RATIO = "sharpe_ratio"
FIELD_EVAL_TRACKING_ERROR = "tracking_error"
FIELD_EVAL_DOWNSIDE_RISK = "downside_risk"


BASIC_POSITON_DESCR_FIELDS = [
    FIELD_DATE,
    FIELD_TICKER,
    FIELD_ISIN,
    FIELD_CCY,
    FIELD_SECURITY_TYPE,
    FIELD_CLOSE,
]

BASIC_MARKET_DATA_INPUT_FIELDS = [
    FIELD_CLOSE,
    FIELD_STOCK_SPLIT,
    FIELD_DIVIDENDS,
    FIELD_FX_RATES,
]

BASIC_POSITION_FIELDS = [
    FIELD_DATE,
    FIELD_TICKER,
    FIELD_ISIN,
    FIELD_CCY,
    FIELD_SECURITY_TYPE,
    FIELD_EVAL_QUANTITY,
]

BASIC_HOLDINGS_FIELDS = [
    FIELD_EVAL_TRANSACTION_PNL,
    FIELD_EVAL_INCOME_PNL,
    FIELD_EVAL_PNL,
    FIELD_EVAL_MKTVALUE,
    FIELD_EVAL_M2M_BOD,
    FIELD_EVAL_TOTAL_RETURN_BASIS,
    FIELD_EVAL_POSITION_BASIS,
    FIELD_EVAL_RETURN_LCL_CCY,
    FIELD_EVAL_RETURN,
    FIELD_EVAL_CCY_RETURN,
    FIELD_EVAL_CTR_TO_RETURN,
    FIELD_EVAL_CTR_TO_RETURN_LCL_CCY,
]


BASIC_PERFORMANCE_DAILY_FIELDS = [
    FIELD_EVAL_QUANTITY,
    FIELD_EVAL_MKTVALUE,
    FIELD_EVAL_MKTVALUE_LCL_CCY,
    FIELD_EVAL_M2M_BOD,
    FIELD_EVAL_TOTAL_RETURN_BASIS,
    FIELD_EVAL_TOTAL_RETURN_BASIS_LCL_CCY,
    FIELD_EVAL_POSITION_BASIS,
    FIELD_EVAL_POSITION_BASIS_LCL_CCY,
    FIELD_EVAL_PNL,
    FIELD_EVAL_RETURN,
    FIELD_EVAL_RETURN_HLDS,
    FIELD_EVAL_RETURN_HLDS_LCL_CCY,
    FIELD_EVAL_TRANSACTION_RETURN,
    FIELD_EVAL_TRANSACTION_RETURN_LCL_CCY,
    FIELD_EVAL_PNL_LCL_CCY,
    FIELD_EVAL_RETURN_LCL_CCY,
    FIELD_EVAL_CCY_RETURN,
    FIELD_EVAL_INCOME_PNL_LCL_CCY,
    FIELD_EVAL_TRANSACTION_PNL_LCL_CCY,
    FIELD_EVAL_INCOME_PNL,
    FIELD_EVAL_TRANSACTION_PNL,
]

PERFORMANCE_FIELDS = [
    FIELD_EVAL_1D_RETURN_LCL_CCY,
    FIELD_EVAL_1W_RETURN_LCL_CCY,
    FIELD_EVAL_1M_RETURN_LCL_CCY,
    FIELD_EVAL_1Q_RETURN_LCL_CCY,
    FIELD_EVAL_1Y_RETURN_LCL_CCY,
    FIELD_EVAL_1D_RETURN,
    FIELD_EVAL_1W_RETURN,
    FIELD_EVAL_1M_RETURN,
    FIELD_EVAL_1Q_RETURN,
    FIELD_EVAL_1Y_RETURN,
    FIELD_EVAL_STD_DEV,
    FIELD_EVAL_STD_DEV_LCL_CCY,
    FIELD_EVAL_VAR_95,
    FIELD_EVAL_VAR_99,
    FIELD_EVAL_MEAN,
    FIELD_EVAL_BETA,
    FIELD_EVAL_SKEWNESS,
    FIELD_EVAL_SHARPE_RATIO,
    FIELD_EVAL_TRACKING_ERROR,
    FIELD_EVAL_DOWNSIDE_RISK
]
# TODO: add StdDev, Downside risk (annualized), Skewness, VaR 95%(Ex-Post), Tracking Error, Sharpe Ratio, Beta

################################  Charactersitics fields

FIELD_EVAL_RATIO_PE = "PE"
FIELD_EVAL_RATIO_PCF = "PCF"
FIELD_EVAL_DIVIDEND_YIELD_TTM = "Dividend_Yield"

FIELD_EVAL_PER_SHARE_DILUTED_EPS = "Diluted_EPS"

FIELD_EVAL_BASIC_AVG_SHARE = "Basic_Average_Shares"
FIELD_EVAL_MARKET_CAP_TTM = "Market_Cap_TTM"
FIELD_EVAL_MARKET_NET_INCOME_TTM = "Net_Income_TTM"

# TODO: ADD HERE ALL THE CHAR INDICATORS THAT HAVE TO BE SUPPORTED.


FIELD_EVAL_BASIC_EPS_TTM = "Basic_EPS_TTM"
FIELD_EVAL_BEGINNING_CASH_POSITION_TTM = "Beginning_Cash_Position_TTM"
FIELD_EVAL_CAPITAL_EXPENDITURE_TTM = "Capital_Expenditure_TTM"
FIELD_EVAL_CASH_DIVIDENDS_PAID_TTM = "Cash_Dividends_Paid_TTM"
FIELD_EVAL_CASH_FLOW_FROM_CONTINUING_FINANCING_ACTIVITIES_TTM = "Cash_Flow_From_Continuing_Financing_Activities_TTM"
FIELD_EVAL_CASH_FLOW_FROM_CONTINUING_INVESTING_ACTIVITIES_TTM = "Cash_Flow_From_Continuing_Investing_Activities_TTM"
FIELD_EVAL_CASH_FLOW_FROM_CONTINUING_OPERATING_ACTIVITIES_TTM = "Cash_Flow_From_Continuing_Operating_Activities_TTM"
FIELD_EVAL_CHANGE_IN_ACCOUNT_PAYABLE_TTM = "Change_In_Account_Payable_TTM"
FIELD_EVAL_CHANGE_IN_INVENTORY_TTM = "Change_In_Inventory_TTM"
FIELD_EVAL_CHANGE_IN_OTHER_CURRENT_ASSETS_TTM = "Change_In_Other_Current_Assets_TTM"
FIELD_EVAL_CHANGE_IN_OTHER_CURRENT_LIABILITIES_TTM = "Change_In_Other_Current_Liabilities_TTM"
FIELD_EVAL_CHANGE_IN_PAYABLE_TTM = "Change_In_Payable_TTM"
FIELD_EVAL_CHANGE_IN_PAYABLES_AND_ACCRUED_EXPENSE_TTM = "Change_In_Payables_And_Accrued_Expense_TTM"
FIELD_EVAL_CHANGE_IN_RECEIVABLES_TTM = "Change_In_Receivables_TTM"
FIELD_EVAL_CHANGE_IN_WORKING_CAPITAL_TTM = "Change_In_Working_Capital_TTM"
FIELD_EVAL_CHANGES_IN_ACCOUNT_RECEIVABLES_TTM = "Changes_In_Account_Receivables_TTM"
FIELD_EVAL_CHANGES_IN_CASH_TTM = "Changes_In_Cash_TTM"
FIELD_EVAL_COMMON_STOCK_DIVIDEND_PAID_TTM = "Common_Stock_Dividend_Paid_TTM"
FIELD_EVAL_COMMON_STOCK_PAYMENTS_TTM = "Common_Stock_Payments_TTM"
FIELD_EVAL_COST_OF_REVENUE_TTM = "Cost_Of_Revenue_TTM"
FIELD_EVAL_DEPRECIATION_AMORTIZATION_DEPLETION_TTM = "Depreciation_Amortization_Depletion_TTM"
FIELD_EVAL_DEPRECIATION_AND_AMORTIZATION_TTM = "Depreciation_And_Amortization_TTM"
FIELD_EVAL_DILUTED_AVERAGE_SHARES_TTM = "Diluted_Average_Shares_TTM"
FIELD_EVAL_DILUTED_NI_AVAILTO_COM_STOCKHOLDERS_TTM = "Diluted_NI_Availto_Com_Stockholders_TTM"
FIELD_EVAL_EBIT_TTM = "EBIT_TTM"
FIELD_EVAL_EBITDA_TTM = "EBITDA_TTM"
FIELD_EVAL_END_CASH_POSITION_TTM = "End_Cash_Position_TTM"
FIELD_EVAL_FINANCING_CASH_FLOW_TTM = "Financing_Cash_Flow_TTM"
FIELD_EVAL_FREE_CASH_FLOW_TTM = "Free_Cash_Flow_TTM"
FIELD_EVAL_GROSS_PROFIT_TTM = "Gross_Profit_TTM"
FIELD_EVAL_INCOME_TAX_PAID_SUPPLEMENTAL_DATA_TTM = "Income_Tax_Paid_Supplemental_Data_TTM"
FIELD_EVAL_INVESTING_CASH_FLOW_TTM = "Investing_Cash_Flow_TTM"
FIELD_EVAL_ISSUANCE_OF_DEBT_TTM = "Issuance_Of_Debt_TTM"
FIELD_EVAL_LONG_TERM_DEBT_ISSUANCE_TTM = "Long_Term_Debt_Issuance_TTM"
FIELD_EVAL_LONG_TERM_DEBT_PAYMENTS_TTM = "Long_Term_Debt_Payments_TTM"
FIELD_EVAL_NET_COMMON_STOCK_ISSUANCE_TTM = "Net_Common_Stock_Issuance_TTM"
FIELD_EVAL_NET_INCOME_COMMON_STOCKHOLDERS_TTM = "Net_Income_Common_Stockholders_TTM"
FIELD_EVAL_NET_INCOME_CONTINUOUS_OPERATIONS_TTM = "Net_Income_Continuous_Operations_TTM"
FIELD_EVAL_NET_INCOME_FROM_CONTINUING_AND_DISCONTINUED_OPERATION_TTM = "Net_Income_From_Continuing_And_Discontinued_Operation_TTM"
FIELD_EVAL_NET_INCOME_FROM_CONTINUING_OPERATION_NET_MINORITY_INTEREST_TTM = "Net_Income_From_Continuing_Operation_Net_Minority_Interest_TTM"
FIELD_EVAL_NET_INCOME_FROM_CONTINUING_OPERATIONS_TTM = "Net_Income_From_Continuing_Operations_TTM"
FIELD_EVAL_NET_INCOME_INCLUDING_NONCONTROLLING_INTERESTS_TTM = "Net_Income_Including_Noncontrolling_Interests_TTM"
FIELD_EVAL_NET_INVESTMENT_PURCHASE_AND_SALE_TTM = "Net_Investment_Purchase_And_Sale_TTM"
FIELD_EVAL_NET_ISSUANCE_PAYMENTS_OF_DEBT_TTM = "Net_Issuance_Payments_Of_Debt_TTM"
FIELD_EVAL_NET_LONG_TERM_DEBT_ISSUANCE_TTM = "Net_Long_Term_Debt_Issuance_TTM"
FIELD_EVAL_NET_OTHER_FINANCING_CHARGES_TTM = "Net_Other_Financing_Charges_TTM"
FIELD_EVAL_NET_OTHER_INVESTING_CHANGES_TTM = "Net_Other_Investing_Changes_TTM"
FIELD_EVAL_NET_PPE_PURCHASE_AND_SALE_TTM = "Net_PPE_Purchase_And_Sale_TTM"
FIELD_EVAL_NET_SHORT_TERM_DEBT_ISSUANCE_TTM = "Net_Short_Term_Debt_Issuance_TTM"
FIELD_EVAL_NORMALIZED_EBITDA_TTM = "Normalized_EBITDA_TTM"
FIELD_EVAL_NORMALIZED_INCOME_TTM = "Normalized_Income_TTM"
FIELD_EVAL_OPERATING_CASH_FLOW_TTM = "Operating_Cash_Flow_TTM"
FIELD_EVAL_OPERATING_EXPENSE_TTM = "Operating_Expense_TTM"
FIELD_EVAL_OPERATING_INCOME_TTM = "Operating_Income_TTM"
FIELD_EVAL_OPERATING_REVENUE_TTM = "Operating_Revenue_TTM"
FIELD_EVAL_OTHER_INCOME_EXPENSE_TTM = "Other_Income_Expense_TTM"
FIELD_EVAL_OTHER_NON_CASH_ITEMS_TTM = "Other_Non_Cash_Items_TTM"
FIELD_EVAL_OTHER_NON_OPERATING_INCOME_EXPENSES_TTM = "Other_Non_Operating_Income_Expenses_TTM"
FIELD_EVAL_PRETAX_INCOME_TTM = "Pretax_Income_TTM"
FIELD_EVAL_PURCHASE_OF_INVESTMENT_TTM = "Purchase_Of_Investment_TTM"
FIELD_EVAL_PURCHASE_OF_PPE_TTM = "Purchase_Of_PPE_TTM"
FIELD_EVAL_RECONCILED_COST_OF_REVENUE_TTM = "Reconciled_Cost_Of_Revenue_TTM"
FIELD_EVAL_RECONCILED_DEPRECIATION_TTM = "Reconciled_Depreciation_TTM"
FIELD_EVAL_REPAYMENT_OF_DEBT_TTM = "Repayment_Of_Debt_TTM"
FIELD_EVAL_REPURCHASE_OF_CAPITAL_STOCK_TTM = "Repurchase_Of_Capital_Stock_TTM"
FIELD_EVAL_RESEARCH_AND_DEVELOPMENT_TTM = "Research_And_Development_TTM"
FIELD_EVAL_SALE_OF_INVESTMENT_TTM = "Sale_Of_Investment_TTM"
FIELD_EVAL_SELLING_GENERAL_AND_ADMINISTRATION_TTM = "Selling_General_And_Administration_TTM"
FIELD_EVAL_SHORT_TERM_DEBT_PAYMENTS_TTM = "Short_Term_Debt_Payments_TTM"
FIELD_EVAL_STOCK_BASED_COMPENSATION_TTM = "Stock_Based_Compensation_TTM"
FIELD_EVAL_TAX_EFFECT_OF_UNUSUAL_ITEMS_TTM = "Tax_Effect_Of_Unusual_Items_TTM"
FIELD_EVAL_TAX_PROVISION_TTM = "Tax_Provision_TTM"
FIELD_EVAL_TAX_RATE_FOR_CALCS_TTM = "Tax_Rate_For_Calcs_TTM"
FIELD_EVAL_TOTAL_EXPENSES_TTM = "Total_Expenses_TTM"
FIELD_EVAL_TOTAL_OPERATING_INCOME_AS_REPORTED_TTM = "Total_Operating_Income_As_Reported_TTM"
FIELD_EVAL_TOTAL_REVENUE_TTM = "Total_Revenue_TTM"

CHARACTERISTICS_FIELDS = [
    FIELD_EVAL_RATIO_PE,
    FIELD_EVAL_RATIO_PCF,
    FIELD_EVAL_PER_SHARE_DILUTED_EPS,
    FIELD_EVAL_BASIC_AVG_SHARE,
    FIELD_EVAL_MARKET_CAP_TTM,
    FIELD_EVAL_MARKET_NET_INCOME_TTM,
    FIELD_EVAL_DIVIDEND_YIELD_TTM,
    FIELD_EVAL_BASIC_EPS_TTM,
    FIELD_EVAL_BEGINNING_CASH_POSITION_TTM,
    FIELD_EVAL_CAPITAL_EXPENDITURE_TTM,
    FIELD_EVAL_CASH_DIVIDENDS_PAID_TTM,
    FIELD_EVAL_CASH_FLOW_FROM_CONTINUING_FINANCING_ACTIVITIES_TTM,
    FIELD_EVAL_CASH_FLOW_FROM_CONTINUING_INVESTING_ACTIVITIES_TTM,
    FIELD_EVAL_CASH_FLOW_FROM_CONTINUING_OPERATING_ACTIVITIES_TTM,
    FIELD_EVAL_CHANGE_IN_ACCOUNT_PAYABLE_TTM,
    FIELD_EVAL_CHANGE_IN_INVENTORY_TTM,
    FIELD_EVAL_CHANGE_IN_OTHER_CURRENT_ASSETS_TTM,
    FIELD_EVAL_CHANGE_IN_OTHER_CURRENT_LIABILITIES_TTM,
    FIELD_EVAL_CHANGE_IN_PAYABLE_TTM,
    FIELD_EVAL_CHANGE_IN_PAYABLES_AND_ACCRUED_EXPENSE_TTM,
    FIELD_EVAL_CHANGE_IN_RECEIVABLES_TTM,
    FIELD_EVAL_CHANGE_IN_WORKING_CAPITAL_TTM,
    FIELD_EVAL_CHANGES_IN_ACCOUNT_RECEIVABLES_TTM,
    FIELD_EVAL_CHANGES_IN_CASH_TTM,
    FIELD_EVAL_COMMON_STOCK_DIVIDEND_PAID_TTM,
    FIELD_EVAL_COMMON_STOCK_PAYMENTS_TTM,
    FIELD_EVAL_COST_OF_REVENUE_TTM,
    FIELD_EVAL_DEPRECIATION_AMORTIZATION_DEPLETION_TTM,
    FIELD_EVAL_DEPRECIATION_AND_AMORTIZATION_TTM,
    FIELD_EVAL_DILUTED_AVERAGE_SHARES_TTM,
    FIELD_EVAL_DILUTED_NI_AVAILTO_COM_STOCKHOLDERS_TTM,
    FIELD_EVAL_EBIT_TTM,
    FIELD_EVAL_EBITDA_TTM,
    FIELD_EVAL_END_CASH_POSITION_TTM,
    FIELD_EVAL_FINANCING_CASH_FLOW_TTM,
    FIELD_EVAL_FREE_CASH_FLOW_TTM,
    FIELD_EVAL_GROSS_PROFIT_TTM,
    FIELD_EVAL_INCOME_TAX_PAID_SUPPLEMENTAL_DATA_TTM,
    FIELD_EVAL_INVESTING_CASH_FLOW_TTM,
    FIELD_EVAL_ISSUANCE_OF_DEBT_TTM,
    FIELD_EVAL_LONG_TERM_DEBT_ISSUANCE_TTM,
    FIELD_EVAL_LONG_TERM_DEBT_PAYMENTS_TTM,
    FIELD_EVAL_NET_COMMON_STOCK_ISSUANCE_TTM,
    FIELD_EVAL_NET_INCOME_COMMON_STOCKHOLDERS_TTM,
    FIELD_EVAL_NET_INCOME_CONTINUOUS_OPERATIONS_TTM,
    FIELD_EVAL_NET_INCOME_FROM_CONTINUING_AND_DISCONTINUED_OPERATION_TTM,
    FIELD_EVAL_NET_INCOME_FROM_CONTINUING_OPERATION_NET_MINORITY_INTEREST_TTM,
    FIELD_EVAL_NET_INCOME_FROM_CONTINUING_OPERATIONS_TTM,
    FIELD_EVAL_NET_INCOME_INCLUDING_NONCONTROLLING_INTERESTS_TTM,
    FIELD_EVAL_NET_INVESTMENT_PURCHASE_AND_SALE_TTM,
    FIELD_EVAL_NET_ISSUANCE_PAYMENTS_OF_DEBT_TTM,
    FIELD_EVAL_NET_LONG_TERM_DEBT_ISSUANCE_TTM,
    FIELD_EVAL_NET_OTHER_FINANCING_CHARGES_TTM,
    FIELD_EVAL_NET_OTHER_INVESTING_CHANGES_TTM,
    FIELD_EVAL_NET_PPE_PURCHASE_AND_SALE_TTM,
    FIELD_EVAL_NET_SHORT_TERM_DEBT_ISSUANCE_TTM,
    FIELD_EVAL_NORMALIZED_EBITDA_TTM,
    FIELD_EVAL_NORMALIZED_INCOME_TTM,
    FIELD_EVAL_OPERATING_CASH_FLOW_TTM,
    FIELD_EVAL_OPERATING_EXPENSE_TTM,
    FIELD_EVAL_OPERATING_INCOME_TTM,
    FIELD_EVAL_OPERATING_REVENUE_TTM,
    FIELD_EVAL_OTHER_INCOME_EXPENSE_TTM,
    FIELD_EVAL_OTHER_NON_CASH_ITEMS_TTM,
    FIELD_EVAL_OTHER_NON_OPERATING_INCOME_EXPENSES_TTM,
    FIELD_EVAL_PRETAX_INCOME_TTM,
    FIELD_EVAL_PURCHASE_OF_INVESTMENT_TTM,
    FIELD_EVAL_PURCHASE_OF_PPE_TTM,
    FIELD_EVAL_RECONCILED_COST_OF_REVENUE_TTM,
    FIELD_EVAL_RECONCILED_DEPRECIATION_TTM,
    FIELD_EVAL_REPAYMENT_OF_DEBT_TTM,
    FIELD_EVAL_REPURCHASE_OF_CAPITAL_STOCK_TTM,
    FIELD_EVAL_RESEARCH_AND_DEVELOPMENT_TTM,
    FIELD_EVAL_SALE_OF_INVESTMENT_TTM,
    FIELD_EVAL_SELLING_GENERAL_AND_ADMINISTRATION_TTM,
    FIELD_EVAL_SHORT_TERM_DEBT_PAYMENTS_TTM,
    FIELD_EVAL_STOCK_BASED_COMPENSATION_TTM,
    FIELD_EVAL_TAX_EFFECT_OF_UNUSUAL_ITEMS_TTM,
    FIELD_EVAL_TAX_PROVISION_TTM,
    FIELD_EVAL_TAX_RATE_FOR_CALCS_TTM,
    FIELD_EVAL_TOTAL_EXPENSES_TTM,
    FIELD_EVAL_TOTAL_OPERATING_INCOME_AS_REPORTED_TTM,
    FIELD_EVAL_TOTAL_REVENUE_TTM,
]

# YoY Constants
FIELD_EVAL_BASIC_EPS_YOY = "Basic_EPS_YOY"
FIELD_EVAL_BEGINNING_CASH_POSITION_YOY = "Beginning_Cash_Position_YOY"
FIELD_EVAL_CAPITAL_EXPENDITURE_YOY = "Capital_Expenditure_YOY"
FIELD_EVAL_CASH_DIVIDENDS_PAID_YOY = "Cash_Dividends_Paid_YOY"
FIELD_EVAL_CASH_FLOW_FROM_CONTINUING_FINANCING_ACTIVITIES_YOY = "Cash_Flow_From_Continuing_Financing_Activities_YOY"
FIELD_EVAL_CASH_FLOW_FROM_CONTINUING_INVESTING_ACTIVITIES_YOY = "Cash_Flow_From_Continuing_Investing_Activities_YOY"
FIELD_EVAL_CASH_FLOW_FROM_CONTINUING_OPERATING_ACTIVITIES_YOY = "Cash_Flow_From_Continuing_Operating_Activities_YOY"
FIELD_EVAL_CHANGE_IN_ACCOUNT_PAYABLE_YOY = "Change_In_Account_Payable_YOY"
FIELD_EVAL_CHANGE_IN_INVENTORY_YOY = "Change_In_Inventory_YOY"
FIELD_EVAL_CHANGE_IN_OTHER_CURRENT_ASSETS_YOY = "Change_In_Other_Current_Assets_YOY"
FIELD_EVAL_CHANGE_IN_OTHER_CURRENT_LIABILITIES_YOY = "Change_In_Other_Current_Liabilities_YOY"
FIELD_EVAL_CHANGE_IN_PAYABLE_YOY = "Change_In_Payable_YOY"
FIELD_EVAL_CHANGE_IN_PAYABLES_AND_ACCRUED_EXPENSE_YOY = "Change_In_Payables_And_Accrued_Expense_YOY"
FIELD_EVAL_CHANGE_IN_RECEIVABLES_YOY = "Change_In_Receivables_YOY"
FIELD_EVAL_CHANGE_IN_WORKING_CAPITAL_YOY = "Change_In_Working_Capital_YOY"
FIELD_EVAL_CHANGES_IN_ACCOUNT_RECEIVABLES_YOY = "Changes_In_Account_Receivables_YOY"
FIELD_EVAL_CHANGES_IN_CASH_YOY = "Changes_In_Cash_YOY"
FIELD_EVAL_COMMON_STOCK_DIVIDEND_PAID_YOY = "Common_Stock_Dividend_Paid_YOY"
FIELD_EVAL_COMMON_STOCK_PAYMENTS_YOY = "Common_Stock_Payments_YOY"
FIELD_EVAL_COST_OF_REVENUE_YOY = "Cost_Of_Revenue_YOY"
FIELD_EVAL_DEPRECIATION_AMORTIZATION_DEPLETION_YOY = "Depreciation_Amortization_Depletion_YOY"
FIELD_EVAL_DEPRECIATION_AND_AMORTIZATION_YOY = "Depreciation_And_Amortization_YOY"
FIELD_EVAL_DILUTED_AVERAGE_SHARES_YOY = "Diluted_Average_Shares_YOY"
FIELD_EVAL_DILUTED_NI_AVAILTO_COM_STOCKHOLDERS_YOY = "Diluted_NI_Availto_Com_Stockholders_YOY"
FIELD_EVAL_EBIT_YOY = "EBIT_YOY"
FIELD_EVAL_EBITDA_YOY = "EBITDA_YOY"
FIELD_EVAL_END_CASH_POSITION_YOY = "End_Cash_Position_YOY"
FIELD_EVAL_FINANCING_CASH_FLOW_YOY = "Financing_Cash_Flow_YOY"
FIELD_EVAL_FREE_CASH_FLOW_YOY = "Free_Cash_Flow_YOY"
FIELD_EVAL_GROSS_PROFIT_YOY = "Gross_Profit_YOY"
FIELD_EVAL_INCOME_TAX_PAID_SUPPLEMENTAL_DATA_YOY = "Income_Tax_Paid_Supplemental_Data_YOY"
FIELD_EVAL_INVESTING_CASH_FLOW_YOY = "Investing_Cash_Flow_YOY"
FIELD_EVAL_ISSUANCE_OF_DEBT_YOY = "Issuance_Of_Debt_YOY"
FIELD_EVAL_LONG_TERM_DEBT_ISSUANCE_YOY = "Long_Term_Debt_Issuance_YOY"
FIELD_EVAL_LONG_TERM_DEBT_PAYMENTS_YOY = "Long_Term_Debt_Payments_YOY"
FIELD_EVAL_NET_COMMON_STOCK_ISSUANCE_YOY = "Net_Common_Stock_Issuance_YOY"
FIELD_EVAL_NET_INCOME_COMMON_STOCKHOLDERS_YOY = "Net_Income_Common_Stockholders_YOY"
FIELD_EVAL_NET_INCOME_CONTINUOUS_OPERATIONS_YOY = "Net_Income_Continuous_Operations_YOY"
FIELD_EVAL_NET_INCOME_FROM_CONTINUING_AND_DISCONTINUED_OPERATION_YOY = "Net_Income_From_Continuing_And_Discontinued_Operation_YOY"
FIELD_EVAL_NET_INCOME_FROM_CONTINUING_OPERATION_NET_MINORITY_INTEREST_YOY = "Net_Income_From_Continuing_Operation_Net_Minority_Interest_YOY"
FIELD_EVAL_NET_INCOME_FROM_CONTINUING_OPERATIONS_YOY = "Net_Income_From_Continuing_Operations_YOY"
FIELD_EVAL_NET_INCOME_INCLUDING_NONCONTROLLING_INTERESTS_YOY = "Net_Income_Including_Noncontrolling_Interests_YOY"
FIELD_EVAL_NET_INVESTMENT_PURCHASE_AND_SALE_YOY = "Net_Investment_Purchase_And_Sale_YOY"
FIELD_EVAL_NET_ISSUANCE_PAYMENTS_OF_DEBT_YOY = "Net_Issuance_Payments_Of_Debt_YOY"
FIELD_EVAL_NET_LONG_TERM_DEBT_ISSUANCE_YOY = "Net_Long_Term_Debt_Issuance_YOY"
FIELD_EVAL_NET_OTHER_FINANCING_CHARGES_YOY = "Net_Other_Financing_Charges_YOY"
FIELD_EVAL_NET_OTHER_INVESTING_CHANGES_YOY = "Net_Other_Investing_Changes_YOY"
FIELD_EVAL_NET_PPE_PURCHASE_AND_SALE_YOY = "Net_PPE_Purchase_And_Sale_YOY"
FIELD_EVAL_NET_SHORT_TERM_DEBT_ISSUANCE_YOY = "Net_Short_Term_Debt_Issuance_YOY"
FIELD_EVAL_NORMALIZED_EBITDA_YOY = "Normalized_EBITDA_YOY"
FIELD_EVAL_NORMALIZED_INCOME_YOY = "Normalized_Income_YOY"
FIELD_EVAL_OPERATING_CASH_FLOW_YOY = "Operating_Cash_Flow_YOY"
FIELD_EVAL_OPERATING_EXPENSE_YOY = "Operating_Expense_YOY"
FIELD_EVAL_OPERATING_INCOME_YOY = "Operating_Income_YOY"
FIELD_EVAL_OPERATING_REVENUE_YOY = "Operating_Revenue_YOY"
FIELD_EVAL_OTHER_INCOME_EXPENSE_YOY = "Other_Income_Expense_YOY"
FIELD_EVAL_OTHER_NON_CASH_ITEMS_YOY = "Other_Non_Cash_Items_YOY"
FIELD_EVAL_OTHER_NON_OPERATING_INCOME_EXPENSES_YOY = "Other_Non_Operating_Income_Expenses_YOY"
FIELD_EVAL_PRETAX_INCOME_YOY = "Pretax_Income_YOY"
FIELD_EVAL_PURCHASE_OF_INVESTMENT_YOY = "Purchase_Of_Investment_YOY"
FIELD_EVAL_PURCHASE_OF_PPE_YOY = "Purchase_Of_PPE_YOY"
FIELD_EVAL_RECONCILED_COST_OF_REVENUE_YOY = "Reconciled_Cost_Of_Revenue_YOY"
FIELD_EVAL_RECONCILED_DEPRECIATION_YOY = "Reconciled_Depreciation_YOY"
FIELD_EVAL_REPAYMENT_OF_DEBT_YOY = "Repayment_Of_Debt_YOY"
FIELD_EVAL_REPURCHASE_OF_CAPITAL_STOCK_YOY = "Repurchase_Of_Capital_Stock_YOY"
FIELD_EVAL_RESEARCH_AND_DEVELOPMENT_YOY = "Research_And_Development_YOY"
FIELD_EVAL_SALE_OF_INVESTMENT_YOY = "Sale_Of_Investment_YOY"
FIELD_EVAL_SELLING_GENERAL_AND_ADMINISTRATION_YOY = "Selling_General_And_Administration_YOY"
FIELD_EVAL_SHORT_TERM_DEBT_PAYMENTS_YOY = "Short_Term_Debt_Payments_YOY"
FIELD_EVAL_STOCK_BASED_COMPENSATION_YOY = "Stock_Based_Compensation_YOY"
FIELD_EVAL_TAX_EFFECT_OF_UNUSUAL_ITEMS_YOY = "Tax_Effect_Of_Unusual_Items_YOY"
FIELD_EVAL_TAX_PROVISION_YOY = "Tax_Provision_YOY"
FIELD_EVAL_TAX_RATE_FOR_CALCS_YOY = "Tax_Rate_For_Calcs_YOY"
FIELD_EVAL_TOTAL_EXPENSES_YOY = "Total_Expenses_YOY"
FIELD_EVAL_TOTAL_OPERATING_INCOME_AS_REPORTED_YOY = "Total_Operating_Income_As_Reported_YOY"
FIELD_EVAL_TOTAL_REVENUE_YOY = "Total_Revenue_YOY"

# Estimate Constants
FIELD_EVAL_EST_EARNINGS_0Q = "Est_Earn_0Q_Avg"
FIELD_EVAL_EST_EARNINGS_1Q = "Est_Earn_1Q_Avg"
FIELD_EVAL_EST_EARNINGS_0Y = "Est_Earn_0Y_Avg"
FIELD_EVAL_EST_EARNINGS_1Y = "Est_Earn_1Y_Avg"
FIELD_EVAL_EST_REVENUE_0Q = "Est_Rev_0Q_Avg"
FIELD_EVAL_EST_REVENUE_1Q = "Est_Rev_1Q_Avg"
FIELD_EVAL_EST_REVENUE_0Y = "Est_Rev_0Y_Avg"
FIELD_EVAL_EST_REVENUE_1Y = "Est_Rev_1Y_Avg"
FIELD_EVAL_EST_GROWTH_0Q = "Est_Growth_0Q"
FIELD_EVAL_EST_GROWTH_1Q = "Est_Growth_1Q"
FIELD_EVAL_EST_GROWTH_0Y = "Est_Growth_0Y"
FIELD_EVAL_EST_GROWTH_1Y = "Est_Growth_1Y"
FIELD_EVAL_EST_GROWTH_5Y = "Est_Growth_5Y"

CHARACTERISTICS_FIELDS.extend([
    FIELD_EVAL_BASIC_EPS_YOY,
    FIELD_EVAL_BEGINNING_CASH_POSITION_YOY,
    FIELD_EVAL_CAPITAL_EXPENDITURE_YOY,
    FIELD_EVAL_CASH_DIVIDENDS_PAID_YOY,
    FIELD_EVAL_CASH_FLOW_FROM_CONTINUING_FINANCING_ACTIVITIES_YOY,
    FIELD_EVAL_CASH_FLOW_FROM_CONTINUING_INVESTING_ACTIVITIES_YOY,
    FIELD_EVAL_CASH_FLOW_FROM_CONTINUING_OPERATING_ACTIVITIES_YOY,
    FIELD_EVAL_CHANGE_IN_ACCOUNT_PAYABLE_YOY,
    FIELD_EVAL_CHANGE_IN_INVENTORY_YOY,
    FIELD_EVAL_CHANGE_IN_OTHER_CURRENT_ASSETS_YOY,
    FIELD_EVAL_CHANGE_IN_OTHER_CURRENT_LIABILITIES_YOY,
    FIELD_EVAL_CHANGE_IN_PAYABLE_YOY,
    FIELD_EVAL_CHANGE_IN_PAYABLES_AND_ACCRUED_EXPENSE_YOY,
    FIELD_EVAL_CHANGE_IN_RECEIVABLES_YOY,
    FIELD_EVAL_CHANGE_IN_WORKING_CAPITAL_YOY,
    FIELD_EVAL_CHANGES_IN_ACCOUNT_RECEIVABLES_YOY,
    FIELD_EVAL_CHANGES_IN_CASH_YOY,
    FIELD_EVAL_COMMON_STOCK_DIVIDEND_PAID_YOY,
    FIELD_EVAL_COMMON_STOCK_PAYMENTS_YOY,
    FIELD_EVAL_COST_OF_REVENUE_YOY,
    FIELD_EVAL_DEPRECIATION_AMORTIZATION_DEPLETION_YOY,
    FIELD_EVAL_DEPRECIATION_AND_AMORTIZATION_YOY,
    FIELD_EVAL_DILUTED_AVERAGE_SHARES_YOY,
    FIELD_EVAL_DILUTED_NI_AVAILTO_COM_STOCKHOLDERS_YOY,
    FIELD_EVAL_EBIT_YOY,
    FIELD_EVAL_EBITDA_YOY,
    FIELD_EVAL_END_CASH_POSITION_YOY,
    FIELD_EVAL_FINANCING_CASH_FLOW_YOY,
    FIELD_EVAL_FREE_CASH_FLOW_YOY,
    FIELD_EVAL_GROSS_PROFIT_YOY,
    FIELD_EVAL_INCOME_TAX_PAID_SUPPLEMENTAL_DATA_YOY,
    FIELD_EVAL_INVESTING_CASH_FLOW_YOY,
    FIELD_EVAL_ISSUANCE_OF_DEBT_YOY,
    FIELD_EVAL_LONG_TERM_DEBT_ISSUANCE_YOY,
    FIELD_EVAL_LONG_TERM_DEBT_PAYMENTS_YOY,
    FIELD_EVAL_NET_COMMON_STOCK_ISSUANCE_YOY,
    FIELD_EVAL_NET_INCOME_COMMON_STOCKHOLDERS_YOY,
    FIELD_EVAL_NET_INCOME_CONTINUOUS_OPERATIONS_YOY,
    FIELD_EVAL_NET_INCOME_FROM_CONTINUING_AND_DISCONTINUED_OPERATION_YOY,
    FIELD_EVAL_NET_INCOME_FROM_CONTINUING_OPERATION_NET_MINORITY_INTEREST_YOY,
    FIELD_EVAL_NET_INCOME_FROM_CONTINUING_OPERATIONS_YOY,
    FIELD_EVAL_NET_INCOME_INCLUDING_NONCONTROLLING_INTERESTS_YOY,
    FIELD_EVAL_NET_INVESTMENT_PURCHASE_AND_SALE_YOY,
    FIELD_EVAL_NET_ISSUANCE_PAYMENTS_OF_DEBT_YOY,
    FIELD_EVAL_NET_LONG_TERM_DEBT_ISSUANCE_YOY,
    FIELD_EVAL_NET_OTHER_FINANCING_CHARGES_YOY,
    FIELD_EVAL_NET_OTHER_INVESTING_CHANGES_YOY,
    FIELD_EVAL_NET_PPE_PURCHASE_AND_SALE_YOY,
    FIELD_EVAL_NET_SHORT_TERM_DEBT_ISSUANCE_YOY,
    FIELD_EVAL_NORMALIZED_EBITDA_YOY,
    FIELD_EVAL_NORMALIZED_INCOME_YOY,
    FIELD_EVAL_OPERATING_CASH_FLOW_YOY,
    FIELD_EVAL_OPERATING_EXPENSE_YOY,
    FIELD_EVAL_OPERATING_INCOME_YOY,
    FIELD_EVAL_OPERATING_REVENUE_YOY,
    FIELD_EVAL_OTHER_INCOME_EXPENSE_YOY,
    FIELD_EVAL_OTHER_NON_CASH_ITEMS_YOY,
    FIELD_EVAL_OTHER_NON_OPERATING_INCOME_EXPENSES_YOY,
    FIELD_EVAL_PRETAX_INCOME_YOY,
    FIELD_EVAL_PURCHASE_OF_INVESTMENT_YOY,
    FIELD_EVAL_PURCHASE_OF_PPE_YOY,
    FIELD_EVAL_RECONCILED_COST_OF_REVENUE_YOY,
    FIELD_EVAL_RECONCILED_DEPRECIATION_YOY,
    FIELD_EVAL_REPAYMENT_OF_DEBT_YOY,
    FIELD_EVAL_REPURCHASE_OF_CAPITAL_STOCK_YOY,
    FIELD_EVAL_RESEARCH_AND_DEVELOPMENT_YOY,
    FIELD_EVAL_SALE_OF_INVESTMENT_YOY,
    FIELD_EVAL_SELLING_GENERAL_AND_ADMINISTRATION_YOY,
    FIELD_EVAL_SHORT_TERM_DEBT_PAYMENTS_YOY,
    FIELD_EVAL_STOCK_BASED_COMPENSATION_YOY,
    FIELD_EVAL_TAX_EFFECT_OF_UNUSUAL_ITEMS_YOY,
    FIELD_EVAL_TAX_PROVISION_YOY,
    FIELD_EVAL_TAX_RATE_FOR_CALCS_YOY,
    FIELD_EVAL_TOTAL_EXPENSES_YOY,
    FIELD_EVAL_TOTAL_OPERATING_INCOME_AS_REPORTED_YOY,
    FIELD_EVAL_TOTAL_REVENUE_YOY,
    FIELD_EVAL_EST_EARNINGS_0Q,
    FIELD_EVAL_EST_EARNINGS_1Q,
    FIELD_EVAL_EST_EARNINGS_0Y,
    FIELD_EVAL_EST_EARNINGS_1Y,
    FIELD_EVAL_EST_REVENUE_0Q,
    FIELD_EVAL_EST_REVENUE_1Q,
    FIELD_EVAL_EST_REVENUE_0Y,
    FIELD_EVAL_EST_REVENUE_1Y,
    FIELD_EVAL_EST_GROWTH_0Q,
    FIELD_EVAL_EST_GROWTH_1Q,
    FIELD_EVAL_EST_GROWTH_0Y,
    FIELD_EVAL_EST_GROWTH_1Y,
    FIELD_EVAL_EST_GROWTH_5Y,
])


################################  computed fields accumulated over time
FIELD_EVAL_ACC_T_PNL = "acc_pnl"
FIELD_EVAL_ACC_T_PNL_LCL_CCY = "acc_pnl_lcl_ccy"
FIELD_EVAL_ACC_T_RETURN = "acc_return"
FIELD_EVAL_ACC_T_RETURN_LCL_CCY = "acc_return_lcl_ccy"
FIELD_EVAL_ACC_T_CCY_RETURN = "acc_ccy_return"
FIELD_EVAL_ACC_T_CTR_TO_RETURN_LCL_CCY = "acc_ctr_to_return_lcl_ccy"
FIELD_EVAL_ACC_T_RETURN_HLDS_LCL_CCY = "acc_return_hlds_lcl_ccy"
FIELD_EVAL_ACC_T_CTR_TO_RETURN_LCL_CCY = "acc_ctr_to_return_lcl_ccy"
FIELD_EVAL_ACC_T_CTR_TO_RETURN = "acc_ctr_to_return"
FIELD_EVAL_ACC_T_RETURN_HLDS = "acc_return_hlds"
FIELD_EVAL_ACC_T_ALLOCATION = "acc_allocation"
FIELD_EVAL_ACC_T_SELECTION = "acc_selection"
FIELD_EVAL_ACC_T_LEVERAGE = "acc_leverage"
FIELD_EVAL_ACC_T_TRANSACTION_RETURN_LCL_CCY = "acc_transaction_return_lcl_ccy"
FIELD_EVAL_ACC_T_TRANSACTION_RETURN = "acc_transaction_return"

ACC_OVER_TIME_FIELDS = [
    FIELD_EVAL_ACC_T_PNL,
    FIELD_EVAL_ACC_T_PNL_LCL_CCY,
    FIELD_EVAL_ACC_T_RETURN,
    FIELD_EVAL_ACC_T_RETURN_LCL_CCY,
    FIELD_EVAL_ACC_T_CCY_RETURN,
    FIELD_EVAL_ACC_T_CTR_TO_RETURN,
    FIELD_EVAL_ACC_T_CTR_TO_RETURN_LCL_CCY,
    FIELD_EVAL_ACC_T_RETURN_HLDS,
    FIELD_EVAL_ACC_T_RETURN_HLDS_LCL_CCY,
    FIELD_EVAL_ACC_T_TRANSACTION_RETURN_LCL_CCY,
    FIELD_EVAL_ACC_T_TRANSACTION_RETURN,
]

ACC_OVER_TIME_DAILY_FIELDS = [
    FIELD_EVAL_PNL,
    FIELD_EVAL_PNL_LCL_CCY,
    FIELD_EVAL_RETURN,
    FIELD_EVAL_RETURN_LCL_CCY,
    FIELD_EVAL_CCY_RETURN,
    FIELD_EVAL_CTR_TO_RETURN,
    FIELD_EVAL_CTR_TO_RETURN_LCL_CCY,
    FIELD_EVAL_RETURN_HLDS,
    FIELD_EVAL_RETURN_HLDS_LCL_CCY,
    FIELD_EVAL_TRANSACTION_RETURN_LCL_CCY,
    FIELD_EVAL_TRANSACTION_RETURN,
]

accumulate_over_time_field_realtion_dict = dict(
    zip(ACC_OVER_TIME_DAILY_FIELDS, ACC_OVER_TIME_FIELDS)
)

################################  Tree fields and position id convention
# Tree field convetion
FIELD_TREE_POSITION_ID = "position_id"
FIELD_TREE_POSITION_ID_PVSB = ".tree"

# Tree prefixes:
TREE_TOP_ROW_ID = ".[top]"
TREE_PORTFOLIO_PREFIX = ".[portfolio]"
TREE_BENCHMARK_PREFIX = ".[benchmark]"

# Tree suffixes:
TREE_BENCHMARK_SUFFIX = "_bench"
TREE_ACTIVE_SUFFIX = "_active"

TREE_NOT_CLASSIFIED_VALUE = "Not Classified"
#################################  Attrbution fields
FIELD_EVAL_ALLOCATION = "allocation"
FIELD_EVAL_SELECTION = "selection"
FIELD_EVAL_LEVERAGE = "leverage"

ATTRIBUTION_INPUT_DAILY_FIELDS = [
    FIELD_EVAL_M2M_BOD,
    FIELD_EVAL_TOTAL_RETURN_BASIS,
    FIELD_EVAL_POSITION_BASIS,
    FIELD_EVAL_RETURN_LCL_CCY,
    FIELD_EVAL_RETURN,
    FIELD_EVAL_TRANSACTION_RETURN,
    FIELD_EVAL_TRANSACTION_RETURN_LCL_CCY,
    FIELD_EVAL_RETURN_HLDS,
    FIELD_EVAL_RETURN_HLDS_LCL_CCY,
    FIELD_EVAL_CTR_TO_RETURN,
    FIELD_EVAL_CTR_TO_RETURN_LCL_CCY,
    FIELD_EVAL_CCY_RETURN,
    FIELD_EVAL_TOTAL_RETURN_BASIS_WEIGHTS,
    FIELD_EVAL_POSITION_BASIS_WEIGHTS,
]

ATTRIBUTION_OUTPUT_DAILY_FIELDS = [
    FIELD_EVAL_ALLOCATION,
    FIELD_EVAL_SELECTION,
    FIELD_EVAL_LEVERAGE,
]

RETURNS_1_BASE = [
    FIELD_EVAL_RETURN,
    FIELD_EVAL_RETURN_LCL_CCY,
    FIELD_EVAL_CCY_RETURN,
    FIELD_EVAL_RETURN_HLDS,
    FIELD_EVAL_RETURN_HLDS_LCL_CCY,
    FIELD_EVAL_CTR_TO_RETURN,
    FIELD_EVAL_CTR_TO_RETURN_LCL_CCY,
    FIELD_EVAL_TRANSACTION_RETURN,
    FIELD_EVAL_TRANSACTION_RETURN_LCL_CCY,
    FIELD_EVAL_RETURN + TREE_BENCHMARK_SUFFIX,
    FIELD_EVAL_RETURN_LCL_CCY + TREE_BENCHMARK_SUFFIX,
    FIELD_EVAL_CCY_RETURN + TREE_BENCHMARK_SUFFIX,
    FIELD_EVAL_RETURN_HLDS + TREE_BENCHMARK_SUFFIX,
    FIELD_EVAL_RETURN_HLDS_LCL_CCY + TREE_BENCHMARK_SUFFIX,
    FIELD_EVAL_CTR_TO_RETURN + TREE_BENCHMARK_SUFFIX,
    FIELD_EVAL_CTR_TO_RETURN_LCL_CCY + TREE_BENCHMARK_SUFFIX,
    FIELD_EVAL_TRANSACTION_RETURN + TREE_BENCHMARK_SUFFIX,
    FIELD_EVAL_TRANSACTION_RETURN_LCL_CCY + TREE_BENCHMARK_SUFFIX,
]
